[package]
name = "ai-author"
version = "0.1.0"
authors = ["huhn511 <huhn.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.14.0"
anyhow = "1.0.40"
tch = "0.3.1"